### ISSUE TITLE
The Submit and Continue Button is  not working though it's loading .... Why?

### ISSUE THREAD

**Issue by Samm0707** [adrianhajdin/healthcare#43]
![Screenshot 2024-08-24 224420](https://github.com/user-attachments/assets/2e309962-c9d5-4024-a8ef-cdcafb3d4090)
**there is no error in the whole project is there any change i need to perform ?**

**Comment by SanadKhan** [comment]
Do you know if submitting does not perform anything? Check whether the button Is clicked by providing a simple console inside the event. Check for database fields they are proper or not If nothing works share more information like code snippet error logs.

**Comment by Pheeleex** [comment]
in my case the console.logs from patientForm is working, but  patients.actions.ts isnt, when i click submit it just keeps loading.

**Comment by Samm0707** [comment]
Yeah same issue keeps on loading

**Comment by SanadKhan** [comment]
Possible issues can be: 
- Storage setup on Appwrite, 
- 'use server' in your actions file, 
- maybe you are not returning anything
OR else share logs or code snippet to understand since I am assuming you have properly cross verified your code

**Comment by Pheeleex** [comment]
It worked for me after i added 'use server' in my patients.actions file, thank you

**Comment by Samm0707** [comment]
@Pheeleex is your project fully functional?

**Comment by Pheeleex** [comment]
Yes it is, everything works fine now.
