### ISSUE TITLE
It's showing that "'newUser' is declared but its value is never read."

### ISSUE THREAD

**Issue by Adityaraizada1** [adrianhajdin/healthcare#44]
![Screenshot 2024-08-26 at 3 58 10 PM](https://github.com/user-attachments/assets/cb768ff5-c97f-4d4c-aa93-753bb1ae549d)

well have done everything but still newUser is not working.

**Comment by theTechbug** [comment]
This Issue is already been fixed
![image](https://github.com/user-attachments/assets/03866785-01b8-4ae5-9333-4cdaf549be7d)
