### ISSUE TITLE
An error occurred while retrieving the patient details: SyntaxError: "undefined" is not valid JSON

### ISSUE THREAD

**Issue by mohamed-abd-elkahlk** [adrianhajdin/healthcare#6]
i received  this error message when i try to make a query to appwrite  i got no response always receive undefined 

this the code 

![code](https://github.com/adrianhajdin/healthcare/assets/115940318/fc67ec78-7355-4009-a6a0-548bd1422dd1)

and i'm sure i have not miss type anything 

![image](https://github.com/adrianhajdin/healthcare/assets/115940318/b339f54a-9808-4438-8cf8-50a576e0b0b8)

can any one help me fixing this error 

update: when i try to make a query with another atributes like email it return a data.

**Comment by ssaintx** [comment]
there is can be some issues with appwrite, try to delete attribute or collection and create it again. or you may also check a receiving data props. if the exported function is working well, theres receiving data may be invalid.

**Comment by mohamed-abd-elkahlk** [comment]
i try all above and it work some time and after that it brokes again

**Comment by sujatagunale** [comment]
@mohamed-abd-elkahlk, if it worked and then broke again, it could be an issue on the Appwrite side. Please raise an issue on their [Discord channel](https://appwrite.io/discord). 

Before that, do verify if you're passing right `userId` to the function and if the same id user is present in Appwrite DB
